apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mailslurper.config" . }}
  labels:
    app: {{ template "mailslurper.name" . }}
    chart: {{ template "mailslurper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: config
data:
  config.json: |
    {
      "wwwAddress": "0.0.0.0",
      "wwwPort": 8080,
      "serviceAddress": "0.0.0.0",
      "servicePort": 8888,
      "wwwPublicURL": "http://mailslurper.local.servicereactor.io",
      "servicePublicURL": "http://douchetrain.local.servicereactor.io/api",
      "smtpAddress": "0.0.0.0",
      "smtpPort": 25,
      "dbEngine": "SQLite",
      "dbHost": "",
      "dbPort": 0,
      "dbDatabase": "./mailslurper.db",
      "dbUserName": "",
      "dbPassword": "",
      "maxWorkers": 1000,
      "keyFile": "",
      "certFile": "",
      "adminKeyFile": "",
      "adminCertFile": "",
      "authenticationScheme": "",
      "authSecret": "",
      "authSalt": "",
      "authTimeoutInMinutes": 120,
      "credentials": {}
    }

---
